n_epochs: 30
batch_size: 32
h: 224
w: 224
lr: 0.001 ## 0.001, 0.0001, 0.00001
optimizer: adam ## adam, sgd
momentum: 0.9
weight_decay: 0
device: "cuda:1"
n_gpus: 1
kernel_size: 3
model: CNN
use_pooling: True
num_kernel_conv_list: [32,64,64]
