n_epochs: 30
batch_size: 32
h: 224
w: 224
lr: 0.001 ## 0.001, 0.0001
optimizer: adam ## adam, sgd
momentum: 0.9
weight_decay: 0  ## 0, 0.001
device: "cuda:0"
n_gpus: 1
model: MLP
h_dim_list: [80,50,40]   ## [20,10], [20,15,10]
